version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - mind-forge-net
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    networks:
      - mind-forge-net
    restart: unless-stopped

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    networks:
      - mind-forge-net
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - eureka-server
    restart: unless-stopped

  text-service:
    build:
      context: ./text-service
    container_name: text-service
    depends_on:
      - config-server
      - eureka-server
      - ollama
    networks:
      - mind-forge-net
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - config-server
      - eureka-server
      - text-service
    networks:
      - mind-forge-net
    restart: unless-stopped

networks:
  mind-forge-net:
    driver: bridge

volumes:
  ollama: