server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: text-service
              uri: lb://text-service
              predicates:
                - Path=/api/text/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka